/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PacchettiRouteImport } from './routes/pacchetti'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogCosaFaUnCopywriterRouteImport } from './routes/blog/cosa-fa-un-copywriter'
import { Route as ApiLeadRouteImport } from './routes/api/lead'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PacchettiRoute = PacchettiRouteImport.update({
  id: '/pacchetti',
  path: '/pacchetti',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCosaFaUnCopywriterRoute = BlogCosaFaUnCopywriterRouteImport.update({
  id: '/blog/cosa-fa-un-copywriter',
  path: '/blog/cosa-fa-un-copywriter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contatti': typeof ContattiRoute
  '/pacchetti': typeof PacchettiRoute
  '/portfolio': typeof PortfolioRoute
  '/servizi': typeof ServiziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lead': typeof ApiLeadRoute
  '/blog/cosa-fa-un-copywriter': typeof BlogCosaFaUnCopywriterRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contatti': typeof ContattiRoute
  '/pacchetti': typeof PacchettiRoute
  '/portfolio': typeof PortfolioRoute
  '/servizi': typeof ServiziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lead': typeof ApiLeadRoute
  '/blog/cosa-fa-un-copywriter': typeof BlogCosaFaUnCopywriterRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contatti': typeof ContattiRoute
  '/pacchetti': typeof PacchettiRoute
  '/portfolio': typeof PortfolioRoute
  '/servizi': typeof ServiziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lead': typeof ApiLeadRoute
  '/blog/cosa-fa-un-copywriter': typeof BlogCosaFaUnCopywriterRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contatti'
    | '/pacchetti'
    | '/portfolio'
    | '/servizi'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/lead'
    | '/blog/cosa-fa-un-copywriter'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contatti'
    | '/pacchetti'
    | '/portfolio'
    | '/servizi'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/lead'
    | '/blog/cosa-fa-un-copywriter'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contatti'
    | '/pacchetti'
    | '/portfolio'
    | '/servizi'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/lead'
    | '/blog/cosa-fa-un-copywriter'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContattiRoute: typeof ContattiRoute
  PacchettiRoute: typeof PacchettiRoute
  PortfolioRoute: typeof PortfolioRoute
  ServiziRoute: typeof ServiziRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiLeadRoute: typeof ApiLeadRoute
  BlogCosaFaUnCopywriterRoute: typeof BlogCosaFaUnCopywriterRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacchetti': {
      id: '/pacchetti'
      path: '/pacchetti'
      fullPath: '/pacchetti'
      preLoaderRoute: typeof PacchettiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/cosa-fa-un-copywriter': {
      id: '/blog/cosa-fa-un-copywriter'
      path: '/blog/cosa-fa-un-copywriter'
      fullPath: '/blog/cosa-fa-un-copywriter'
      preLoaderRoute: typeof BlogCosaFaUnCopywriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContattiRoute: ContattiRoute,
  PacchettiRoute: PacchettiRoute,
  PortfolioRoute: PortfolioRoute,
  ServiziRoute: ServiziRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiLeadRoute: ApiLeadRoute,
  BlogCosaFaUnCopywriterRoute: BlogCosaFaUnCopywriterRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
